### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/mask#10]
Currently, this is unknown. I'm pretty sure the executor logic will need to be adjusted for Windows.

**Comment by Coteh** [comment]
FWIW, I tried removing all paths to `sh.exe` from my system (i.e. removing paths such as `C:\Program Files\Git\cmd` which contains the Git for Windows version of sh, as well as renaming other instances of `sh.exe` on my system that were being picked up like the ones included with Cmder), ensured that `sh` was no longer being referenced by running `where sh`, then tried running `mask`. I found that the program seems to exit without doing anything nor does it print any sort of error to the terminal.

**Comment by jakedeichert** [comment]
Thanks for checking this! So it sounds like `mask` works with the git bash shell and probably also Ubuntu on Windows.

**Comment by jakedeichert** [comment]
Oh i misread this clearly. Sounds like mask does not work on windows.

**Comment by KsRyY** [comment]
@jakedeichert I suppose if we add PowerShell as a scripting runtime, this could be solved.

**Comment by jakedeichert** [comment]
Adding PowerShell support will probably be useful to people 👍 

But mask should also work with WSL and bash/sh scripting. I have a feeling it's also not handling Windows paths correctly...

**Comment by tensor-programming** [comment]
We're adding mask to our project Tauri, and the powershell support works out of the box it seems.  If I add a block to the maskfile.md in the mask repo, that just looks like this:
```
~~~powershell
Write-Output "Test Output"
cargo build --release
~~~
```
it runs without an issue.

**Comment by jakedeichert** [comment]
@tensor-programming wow, really? That must mean that [powershell supports a -c arg](https://github.com/jakedeichert/mask/blob/master/src/executor.rs#L56-L61)?

I googled this and can't find anything about `powershell -c`. That's really good to know if it works.

Does WSL/bash on windows work too?

I maybe can close this issue if both work :)

**Comment by tensor-programming** [comment]
The `-c` in powershell is short for `-Command`. 

WSL does work out of the box without any changes.  With the PR I made for powershell, I did have to do a little tweaking with the parser to have it ignore powershell and Batch blocks on Linux/WSL.  On windows, it ignores shell blocks automatically for some reason which is a nice side effect.

**Comment by tensor-programming** [comment]
Submitted my PR.  If you want, I can add a github action to test and build mask on Windows.

**Comment by jakedeichert** [comment]
Reopening until I fix the issue with mask on macOS

**Comment by tensor-programming** [comment]
Ahh, something I couldn't test.  Ill have to get one of my devs to take a look from a mac perspective.

**Comment by jakedeichert** [comment]
@tensor-programming no worries at all! I usually test PRs locally but forgot to in this case :)

I'll work on the macOS issue this weekend hopefully 🤞

**Comment by jakedeichert** [comment]
Release as v0.8.0! https://github.com/jakedeichert/mask/releases/tag/v0.8.0
