### ISSUE TITLE
Automate releases and produce binaries for mac and linux

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/mask#11]
I'll need to do some research on best practices here and how other projects do this.

**Comment by DrSensor** [comment]
FYI, there is an action just to upload a release asset (doesn't support multiple release assets yet).
https://github.com/marketplace/actions/upload-a-release-asset

**Comment by jakedeichert** [comment]
@DrSensor i missed that one! I saw a few custom implementations others have done and recreated it myself. Though with the one you linked, it looks like it depends on also creating a release automatically (`upload_url: ${{ steps.create_release.outputs.upload_url }}`)

My plan here is to manually create a new github release which will trigger an auto publish to cargo + upload the binaries to the release.

I'm almost done. I just need to do a macos target tomorrow 👍

**Comment by DrSensor** [comment]
Bad news, [`macos-latest`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#macos-1015) doesn't include Rust by default :sweat_smile: 
Maybe installing `rustup` manually might works :thinking:

**Comment by jakedeichert** [comment]
Got macos building and attaching the binary to the release!

See the config [here](https://github.com/jakedeichert/mask/blob/master/.github/workflows/release.yml#L34-L64).

**Comment by jakedeichert** [comment]
This task is now done 🎉

**Comment by jakedeichert** [comment]
Here's an example. Going to delete this release now and then prep a real 0.7.1 release this week after merging the currently open PR.

<img width="1195" alt="Screen Shot 2019-11-20 at 1 03 52 PM" src="https://user-images.githubusercontent.com/1631044/69264891-3925cd00-0b96-11ea-9537-0b39b04e4de8.png">
