### ISSUE TITLE
Add `number` type to options for input validation purposes

### ISSUE THREAD

**Issue by jakedeichert** [jakedeichert/mask#3]
The port option below has `type: number` which would allow us to validate the input is correct.

Note that even though we can at least validate it, it still gets turned into an environment variable which is just a string. The benefit here is that the script can assume it's always a number and cast it as such.

```md
## serve

**OPTIONS:**
* port
    * flags: -p --port
    * type: number
    * desc: Which port to serve on

~~~node
const port = Number(process.env.port);
console.log(port * 2)
~~~
```

**Comment by makeco** [comment]
Can `type` be a URL or a regular expression?

**Comment by jakedeichert** [comment]
We can definitely add other `type`s for validation purposes. `type: number` would validate the input is a number... so `type: url` could validate the input is a correctly formatted url and `type: path` could also be handy. 

Allowing `type: /^some_regex$/` could be powerful but might be overkill if we can get away with mostly high-level types 👍
