### ISSUE TITLE
Bug: 0.7.0 will not compile with latest from rustup

### ISSUE THREAD

**Issue by raguay** [jakedeichert/mask#40]
I just updated using rustup and noticed that I'm behind in mask versions. So, I went to update and this is what I get:

error[E0432]: unresolved import `self::std::hint`
  --> /Users/raguay/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:13:16
   |
13 | use self::std::hint::unreachable_unchecked;
   |                ^^^^ Could not find `hint` in `std`

error: aborting due to previous error

error: Could not compile `lazy_static`.

I'm not a rust programmer, so I'm not sure how to fix this. Has anyone else seen it? Dropping back to using maid until I can get mask to build again ☹️.

**Comment by jakedeichert** [comment]
Hey @raguay, just saw this. 

How did you go about updating to the latest mask? With `cargo install mask --force` ?

And could you post your rustup, rustc and cargo versions?

**Comment by raguay** [comment]
I found my issue. I had two different rust systems: one in /usr/local/bin and another in ~/.cargo. When I used rustup to update, I had no idea it wasn't updating the version that my command line found first. Now, it is working. Sorry for troubling you.
