### ISSUE TITLE
Publish to homebrew?

### ISSUE THREAD

**Issue by mrmurphy** [jakedeichert/mask#44]
Wow, this project looks great. I used to use maid, and was bummed to see that it doesn't appear to be actively maintained anymore. It might lower the barrier to entry a bit for mask if it offered a brew formula, so I thought I'd create an issue and bring up the idea.

**Comment by jakedeichert** [comment]
Hey, thanks! Publishing on homebrew would be cool with me. Though i use homebrew a little bit, i haven't yet learned about the process to get something published on there.

Added the "help wanted" label, if anyone is interested!

**Comment by brandonkal** [comment]
One option: GoReleaser does this quite well. Once you have the rust binary, GoReleaser can handle publishing the Homebrew formula in CI.
https://medium.com/@jondot/shipping-rust-binaries-with-goreleaser-d5aa42a46be0

**Comment by jakedeichert** [comment]
Now published on homebrew thanks to @vladimyr !

Related PR: https://github.com/jakedeichert/mask/pull/63
