### ISSUE TITLE
Options ignored if - bullets are used [bug]

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#50]
Prettier prefers bullets with the `-` character in markdown rather than `*`. Unfortunately, mask's parser appears to ignore this.

**Comment by jakedeichert** [comment]
This seems to work for me!

<img width="402" alt="Screen Shot 2020-03-17 at 9 55 37 PM" src="https://user-images.githubusercontent.com/1631044/76917531-12ed1100-689a-11ea-95cc-ae01f66c4afc.png">

When filing a bug, please copy/paste a minimum example maskfile so I can test.
