### ISSUE TITLE
Prettier readme

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#52]
Are you fine with making the readme markdown Prettier compliant?

It mostly wants to remove extra whitespace, use "`" over "~" and prefer "-" over "*". I can make a separate PR for that. It would make contributing changes easier.

**Comment by jakedeichert** [comment]
I LOVE prettier but I always disable it for markdown files... I really don't like its styling choices :(

I understand updating the readme might be annoying, but I can handle that if it's too painful.

**Comment by brandonkal** [comment]
Let's commit a `.prettierignore` then.
