### ISSUE TITLE
Interactive experience

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#53]
As you can tell by the other issues I've opened, I really like mask.

One idea I had was to have a sort of interactive installer or tutorial that people could write in markdown.

So a blog post could have this at the top:

> This post is available as an interactive tutorial.
> Run `curl https://example.com/bootstrap-mac.mask.md | mask -i --maskfile-` to get started.

Then it would just work from top to bottom. It would display the markdown for a step rendered with something like [mdcat](https://github.com/lunaryorn/mdcat) as a library. The user would see the code block or commands. It would then prompt for all flag and parameter values. The user would have the option to execute the step or skip to the next one.

This one is more ambitious so if this is not something you want, I can fork mask and build it there. Though it does only require one additional global flag.

This could be useful for tutorials, posts, and even project readme's. I do find it odd that as a whole we have a lot of readme's and documentation that is not executable. Mask is the closest thing I've seen to that concept.

**Comment by jakedeichert** [comment]
Don't really see the need for an interactive experience -- I feel like the README does a good enough walk-through.
