### ISSUE TITLE
Command alias proposal

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#54]
Subcommand aliases can be specified by separating the command name with "//".
So `# command (arg)` becomes `# command//c (arg)`

This is an idea from #51.

Why two slashes?
1. One forward slash doesn't visually provide enough distinction
2. I also considered `# command [c] (arg)` but having a space makes it look like a subcommand and it is easier to accidentally create a markdown link: `# command [c](arg)`

**Comment by jakedeichert** [comment]
Hey Brandon, I just noticed you forked mask into inkjet. Thank you for the attribution in the README 👍 

I'm going to close this as I'm not a big fan of command aliases and it looks like you've implemented it over there.
