### ISSUE TITLE
Default target

### ISSUE THREAD

**Issue by brandonkal** [jakedeichert/mask#55]
Make runs the first target automatically if the target is unspecified.

This would be a useful feature especially when switching between projects.

Alternatively, mask could support a syntax like this:

```md
## \_default

~~~sh
$MASK build
~~~

## build

~~~sh
echo "Running build"
sleep 10
echo "Build Complete"
~~~
```

Then, if no subcommand is specified and a `_default` or `default` command exists, it will be used.

Though the issue with the above is
1. It is rather verbose
2. Passing arguments and keeping those in sync with the default command is difficult.

So a solution to the above issue is that aliases could be supported:

```md
## build//\_default

~~~sh
echo "Running build"
sleep 10
echo "Build Complete"
~~~
```

This proposal relies on my hidden command proposal and alias proposal.

Having an explicit default rather than taking the first command specified appears to be the best approach. For projects that do not implement a default command, an error is displayed. For those that do, `mask` in any folder will do something useful.

**Comment by cherusk** [comment]
Wondering added value, it's only about aligning with make genes which is unnecessary in my eyes. mission of mask is explicitness. How is this any better than calling explicit `mask default` in spots where you want to default.

**Comment by brandonkal** [comment]
That's fine. But this change was about convenience. In my fork I ended up using the explicit alias to `_default`.
