### ISSUE TITLE
feature: introduce concept of named parameters instead of optional parameters

### ISSUE THREAD

**Issue by cherusk** [jakedeichert/mask#61]
I don't like the delineation of optional/positional. Optionality should be a trait of the parameter, indifferent of how it is passed.

Hence, new delineation would be positional or named, the current "optional".

That's how argparse[1] does it essentially.

[1] https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_argument

**Comment by jakedeichert** [comment]
Hmmm not quite sure if I'm missing something here... but I think "named parameters" is the same thing as [optional flags](https://github.com/jakedeichert/mask#optional-flags). 

The idea with positional required/[optional](https://github.com/jakedeichert/mask/issues/5) args is that they are for really simple cases. If you need more complex parameters, then optional flags might be better. 

Do you maybe want the ability to mark certain flags as required?

**Comment by cherusk** [comment]
> Hmmm not quite sure if I'm missing something here... but I think
> "named parameters" is the same thing as optional flags
> <https://github.com/jakedeichert/mask#optional-flags>.
>
> The idea with positional required/optional
> <https://github.com/jakedeichert/mask/issues/5> args is that they are
> for really simple cases. If you need more complex parameters, then
> optional flags might be better.
>
It's not the same.
>
> Do you maybe want the ability to mark certain flags as required?
>
Exactly, but that goes not only for "named", but also for positional
params. Ok, one can reflect that in the backend logic again of course.

**Comment by jakedeichert** [comment]
> Exactly, but that goes not only for "named", but also for positional
params.

So positional args are already *always* required.

For optional flags, apparently [clap does support making flags required](https://docs.rs/clap/2.33.2/clap/struct.Arg.html#method.required). 


I think we can support this by adding a new field to our optional flag definition:

```markdown
## cmd

**OPTIONS**
* check
    * flags: -c --check
    * desc: Show which files are not formatted correctly
    * required
```

If our parser finds `* required`, then the flag is marked as required.

Pretty easy to support if anyone wants to make a PR 👍

**Comment by cherusk** [comment]
> So positional args are already _always_ required.
> 

Find that wrong though as said.

> 
> Pretty easy to support if anyone wants to make a PR +1

Will implement it.

**Comment by cherusk** [comment]
Clap is amazing. :)

**Comment by jakedeichert** [comment]
Marking as closed due to https://github.com/jakedeichert/mask/pull/74

Aiming for a release this week.
