### ISSUE TITLE
feature: interpreter conform syntax highlighting

### ISSUE THREAD

**Issue by cherusk** [jakedeichert/mask#62]
Could go hand in hand with introducing another suffix than `.md` for differentiating, I can imagine `.mask`. The suffix could allow for a custom syntax highlighting scheme of editors.

Find it annoying to look at the `.md` highlighting for the different interpreters, especially for more demanding maskfiles.

Hence, this feature request is about properly highlighting of interpreter code stretches in
`~~~interpreter
~~~` sections.

**Comment by jakedeichert** [comment]
In VS Code, you can actually tell it how to treat specific filename patterns.

**Example:**

```json
"files.associations": {
    "*.template": "json",
    "*.env": "ini",
    "maskfile.md": "maskfile" -- a custom plugin could handle this
  },
```

Someone could make an extension that handles maskfile highlighting (in a different way than normal markdown formatting) and automate this file association.

I'm assuming other editors probably have a way to do this as well?

**Comment by cherusk** [comment]
> I'm assuming other editors probably have a way to do this as well?

Yes was thinking of VIM specifically. Not certain if one can specify more than a suffix for triggering syntax highlighting there, hence my suffix proposal. Will do recherche.

**Comment by jakedeichert** [comment]
Going to close this. I think mask sticking with markdown syntax is ideal, instead of creating our our `.mask` extension. 

If you or someone does create a mask-specialized markdown syntax highlighting scheme/plugin, I'll be happy to link it from the README :)
