### ISSUE TITLE
Document boolean optional flags

### ISSUE THREAD

**Issue by cherusk** [jakedeichert/mask#67]
Having only int and str as **type** is meagre and should be extended to e.g. bool.

**Comment by jakedeichert** [comment]
Bools are supported, just don't put a `type`.

```
**OPTIONS**
* test
    * flags: -t --test
    * desc: Also run the tests

~~~bash
[[ "$test" == "true" ]] && echo "RUNNING TESTS"
~~~
```

**Comment by jakedeichert** [comment]
Added a boolean example to the docs: https://github.com/jakedeichert/mask#optional-flags
