### ISSUE TITLE
feature: align as much as possible with python argparse implementation for param passing behaviour

### ISSUE THREAD

**Issue by cherusk** [jakedeichert/mask#68]
I've already created issues which fall into that category. For preventing me to create a ticket for each individual feature, I'd ask in this umbrella ticket to align as much technically relevant to align with the brilliant [argparse](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_argument) module.

Great features also well suiting  mask are **choices**, specifying param quantity /frequency ...

**Comment by jakedeichert** [comment]
As far as aligning completely with an existing tool goes, like argparse, that's unlikely to happen.

Right now, mask is taking advantage of [clap](https://github.com/clap-rs/clap) for argument and command parsing. If clap doesn't support a feature, mask will not either in most cases. I want to continue to keep mask maintenance as light as possible by relying on popular, existing cli parsers as much as possible. If newer/better cli parsers emerge in the future with more features, I'm happy to switch to them if the benefits outweigh the cons of doing so.

If there's specific features you would like to see, feel free to create issues for them. But if clap doesn't support them, then it's very likely they will not be implemented unless clap or some better cli parser does.

**Comment by cherusk** [comment]
Unbelievable. :disappointed:
