### ISSUE TITLE
Cargo test fails on `env_var_mask:works_from_any_dir`

### ISSUE THREAD

**Issue by twitu** [jakedeichert/mask#69]
```
failures:

---- env_var_mask::works_from_any_dir stdout ----
thread 'env_var_mask::works_from_any_dir' panicked at 'Unexpected stdout, failed var.contains("tests passed")
└── var as str: 

command=`"/home/twitu/Code/mask/target/debug/mask" "--maskfile" "/tmp/.tmpgB48C0/maskfile.md" "ci"`
code=127
stdout=``````
stderr=```bash: mask: command not found
```
If I understand correctly it's failing simply because mask executable is not installed `$PATH`. I tried running this after doing `cargo install mask` and the test passed. 

Should a source code test depend on the executable being installed externally? If this is the desired behaviour it could be mentioned in the README somewhere that the executable should be installed before running tests.

Mask version: 7c316514bbdfbb73bad723b1c28a5436cb27a945
Cargo version: 1.43.0
OS: Ubuntu 20.04
Terminal: zsh

**Comment by jakedeichert** [comment]
Ahhh this is a lack of documentation I think. I usually run `mask link` and then `mask test`... but that depends on mask being installed first....


I'll update the contributing docs
