### ISSUE TITLE
Arguments don't work in Powershell

### ISSUE THREAD

**Issue by berwyn** [jakedeichert/mask#81]
I'm using Mask on Windows 10 and have a task in my `maskfile.md` that accepts an argument, however this seems to be empty when tested in the script. I've tested both the legacy Powershell that ships with the system (some flavour of 5.1) and the current preview release of the modern Powershell and in both cases Powershell will just output an empty line.

OS: Windows 10 21313.1000
Shell: Powershell 5.1.21313.100, Powershell 7.2.0-preview.3

```md
# Powershell example
## powershell legacy (value)
> 5.1.21313.100
~~~powershell
Get-Host | Select-Object Version
Write-Output "${value}"
~~~

## powershell modern (value)
> 7.2.0-preview.3
~~~pwsh
Get-Host | Select-Object Version
Write-Output "${value}"
~~~
```

**Comment by jakedeichert** [comment]
Hmmm, I don't know too much about powershell, but I think you might need to access env variables like this?

```powershell
param (
    $maskfile_command = $env:maskfile_command,
    $value = $env: value
)
```

I'm not 100% certain though. I just grabbed this from our [maskfile.md](https://github.com/jakedeichert/mask/blob/master/maskfile.md) which includes powershell blocks for Windows: 

<img width="1077" alt="Screen Shot 2021-03-05 at 10 02 25 AM" src="https://user-images.githubusercontent.com/1631044/110133111-e62b5580-7d99-11eb-8e67-03fc937cd6cd.png">


If this works, let me know and I can probably improve the README documentation with an example!

**Comment by berwyn** [comment]
Aha, right! It totally went over my head that they're environment variables and that they need to be addressed as such! For some reason, I was thinking they were being passed as params. Thanks for the clarification, and sorry to distract you with a misunderstanding on my part!
